### ISSUE TITLE
Errata de `mixinis` que debe ser llamado `mixins`

### ISSUE THREAD

**Issue by maogongzi** [1950Labs/vuejs.org#137]
En el sección "Extends" hay una errata de `mixinis` que debe ser llamado `mixins`

https://github.com/1950Labs/vuejs.org/blob/master/src/v2/api/index.md#extends

**Comment by sxcamacho** [comment]
Hey @maogongzi, thanks for creating the issue.
I created the pr [140](https://github.com/1950Labs/vuejs.org/pull/140) to fix this typo.
